name = "affsiteadmin"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "MGR_DB"
database_name = "affsite-mgr-db"
database_id = "caa38486-3537-46db-a6fd-c60533f41492"

